apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topics.kafkarator.nais.io
spec:
  group: kafkarator.nais.io
  names:
    kind: Topic
    listKind: TopicList
    plural: topics
    singular: topic
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
