name: Deploy

env:
  BASEIMAGE: docker.pkg.github.com/${{ github.repository }}/nada-kafkarator

on:
  push:
    branches:
      - master

defaults:
  runs-on: ubuntu-latest

jobs:
  setup:
    steps:
      - name: Declare image ref
        run: echo "::set-output name=image::${BASEIMAGE}:$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
  build:
    needs: setup
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build docker image
        run: docker build --tag ${IMAGE} --tag ${BASEIMAGE}:latest .
      - name: Publish docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${BASEIMAGE}
  deploy-dev:
    needs:
      - setup
      - build
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to dev gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml
  deploy-prod:
    needs:
      - setup
      - deploy-dev
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to prod gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
