name: Deploy

env:
  BASEIMAGE: docker.pkg.github.com/${{ github.repository }}/nada-kafkarator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"
      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$BASEIMAGE:$TAG"
      - name: Build docker image
        run: docker build --tag ${IMAGE} --tag ${BASEIMAGE}:latest .
      - name: Publish docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${BASEIMAGE}
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$BASEIMAGE:$TAG"

      - name: Deploy to dev gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$BASEIMAGE:$TAG"

      - name: Deploy to prod gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
